# Generated by Django 5.1.2 on 2024-12-07 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_category_tag_news_category_news_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="news.category",
                verbose_name="Категория",
            ),
        ),
    ]
